["autoload/SpaceVim/api/*.vim"]
alternate = "test/api/{}.vader"

["autoload/SpaceVim/plugins/*.vim"]
alternate = "test/plugin/{}.vader"
lua = "lua/spacevim/plugin/{}.lua"

["lua/spacevim/plugin/*.lua"]
alternate = "test/lua/plugin/{}.vader"
vim = "autoload/SpaceVim/plugins/{}.vim"

["test/plugin/*.vader"]
alternate = "autoload/SpaceVim/plugins/{}.vim"

["test/lua/plugin/*.vader"]
alternate = "lua/spacevim/plugin/{}.lua"

["test/api/*.vader"]
alternate = "autoload/SpaceVim/api/{}.vim"

["doc/*.txt"]
alternate = "doc/{}.cnx"

["doc/*.cnx"]
alternate = "doc/{}.txt"

["wiki/en/Project-layout.md"]
alternate = "wiki/cn/Project-layout.md"

["wiki/cn/Project-layout.md"]
alternate = "wiki/en/Project-layout.md"

["wiki/en/Following-HEAD.md"]
alternate = "wiki/cn/Following-HEAD.md"

["wiki/cn/Following-HEAD.md"]
alternate = "wiki/en/Following-HEAD.md"

["README.md"]
alternate = "README.cn.md"

["README.cn.md"]
alternate = "README.md"
